name: Verify Parity Between Nova/Circle Binaries

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the Nova artifact uploaded to GitHub"
        default: ""
        type: string
      container-image:
        description: "Container Image to use"
        default: ""
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
    steps:
      - name: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: nova
      - name: Unpack Nova Binary
        run: |
          set -ex
          unzip ${{ inputs.artifact-name }} "*" -d "./nova"
          pushd nova
          mkdir extracted
          WHEEL_NAME=$(ls "./")
          python3 -m zipfile --extract "$WHEEL_NAME" extracted/
          popd
      - name: Fetch CircleCI Binary
        run: |
          set -ex
          mkdir circle
          curl https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.13.0.dev20220928%2Bcpu-cp38-cp38-linux_x86_64.whl --output circle/wheel.whl
      - name: Unpack CircleCI Binary
        run: |
          set -ex
          pushd circle
          mkdir extracted
          python3 -m zipfile --extract wheel.whl extracted/
          popd
      - name: Run Verification
        run: |
          set -ex
          pushd circle/extracted
          find . -name "*.so" > $HOME/circle_so_sizes.txt
          find . -name "*.so" | xargs du -sc > $HOME/circle_so_names.txt
          CIRCLE_NUM_SYMBOLS=$(nm ./torchaudio/_torchaudio.so)
          ldd ./torchaudio/_torchaudio.so > $HOME/circle_ldd_dump.txt
          popd
          
          pushd nova/extracted
          find . -name "*.so" > $HOME/nova_so_names.txt
          find . -name "*.so" | xargs du -sc > $HOME/nova_so_names.txt
          NOVA_NUM_SYMBOLS=$(nm ./torchaudio/_torchaudio.so)
          ldd ./torchaudio/_torchaudio.so > $HOME/nova_ldd_dump.txt
          popd
          
          echo "CIRCLE_NUM_SYMBOLS:"
          echo "$CIRCLE_NUM_SYMBOLS"
          echo "NOVA_NUM_SYMBOLS"
          echo "$NOVA_NUM_SYMBOLS"
          cat $HOME/circle_so_names.txt
          cat $HOME/nova_so_names.txt
          diff $HOME/circle_so_names.txt $HOME/nova_so_names.txt
          cat $HOME/circle_so_sizes.txt
          cat $HOME/nova_so_sizes.txt
          diff $HOME/circle_so_sizes.txt $HOME/nova_so_sizes.txt
          cat $HOME/circle_ldd_dump.txt
          cat $HOME/nova_ldd_dump.txt
          diff $HOME/circle_ldd_dump.txt $HOME/nova_ldd_dump.txt

